In [39]:
%pylab inline
import pandas as pd
import seaborn as sns

Populating the interactive namespace from numpy and matplotlib


In [40]:
from sklearn.datasets import load_iris
iris = load_iris()

In [41]:
X= iris.data
y= iris.target
print(X)
print(y)


[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5



**Perform KNN on Iris data**



In [42]:
from sklearn.neighbors import KNeighborsClassifier

In [43]:
knn= KNeighborsClassifier(n_neighbors=5)

In [44]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [45]:
y_pred = knn.predict(X)
print(metrics.accuracy_score(y, y_pred))

0.966666666667


In [46]:
#knn = 1 will alway have 100% accuracy on the TRAINING data
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X,y)
y_pred = knn.predict(X)
print(metrics.accuracy_score(y, y_pred))

1.0




**Perform LR on Iris data**



In [57]:
from sklearn.linear_model import LogisticRegression
lr= LogisticRegression()
lr.fit(X,y)
lr.predict(x_new)

NameError: name 'x_new' is not defined

In [48]:
y_pred = lr.predict(X)
print(y_pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 2 1 1 1
 1 1 1 1 1 1 1 1 1 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [49]:
from sklearn import metrics
print(metrics.accuracy_score(y, y_pred))

0.96


In [50]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state= 4)

In [51]:
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
print(metrics.accuracy_score(y_pred, y_test))

0.95


In [52]:
knn = KNeighborsClassifier(n_neighbors = 6)
knn.fit(X_train, y_train)
y_pred= knn.predict(X_test)
print(metrics.accuracy_score(y_pred, y_test))

0.983333333333


In [53]:
bestknn=[]
for i in range(1,26):
    knn = KNeighborsClassifier(n_neighbors = i)
    knn.fit(X_train, y_train)
    y_pred= knn.predict(X_test)
    bestknn.append(metrics.accuracy_score(y_pred, y_test))
choose=[] 
for i in range(len(bestknn)):
    if bestknn[i] == max(bestknn):
        choose.append(i+1)
choose



[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19]

In [54]:
for i in bestknn:
    print(i)

0.95
0.95
0.966666666667
0.966666666667
0.966666666667
0.983333333333
0.983333333333
0.983333333333
0.983333333333
0.983333333333
0.983333333333
0.983333333333
0.983333333333
0.983333333333
0.983333333333
0.983333333333
0.983333333333
0.966666666667
0.983333333333
0.966666666667
0.966666666667
0.966666666667
0.966666666667
0.95
0.95


Now as the best KNN model has been found (KNN =11 (or 6,7...), the model should again be fitted using ALL the data.

As the train-test-split method is a high variance method (it will have different results depending on how data is split)- Therefore, crossvalidation will be shown here which bypasses this effect...

In [55]:
from sklearn.cross_validation import cross_val_score
knn = KNeighborsClassifier(n_neighbors = 5)
scores = cross_val_score(knn, X, y, cv= 10, scoring="accuracy")
print(scores)

[ 1.          0.93333333  1.          1.          0.86666667  0.93333333
  0.93333333  1.          1.          1.        ]


In [56]:
k_range = range(1,31)
k_scores = []
for k in k_range:
    knn = KNeighborsClassifier(n_neighbors = k)
    k_scores.append(np.mean(cross_val_score(knn, X, y, cv=10, scoring ="accuracy")))
for k in k_scores:
    print(k)

0.96
0.953333333333
0.966666666667
0.966666666667
0.966666666667
0.966666666667
0.966666666667
0.966666666667
0.973333333333
0.966666666667
0.966666666667
0.973333333333
0.98
0.973333333333
0.973333333333
0.973333333333
0.973333333333
0.98
0.973333333333
0.98
0.966666666667
0.966666666667
0.973333333333
0.96
0.966666666667
0.96
0.966666666667
0.953333333333
0.953333333333
0.953333333333
